#这是作为客户端的配置
[default]
log_level = 2
reject_nil_sni = false
daemon_stderr = "./goproxy-vps.log"


[http]
#本地http代理监听端口
listen = ":8087"
#HTTP2模式
#parent_proxy = "https+h2://mc.8932.pw"
#HTTPS模式
#parent_proxy = "https://mc.8932.pw"
#QUIC模式，相当于ss+kcptun
parent_proxy = "quic://mc.8932.pw"
